//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachFile
    {
        public int ID_AttachID { get; set; }
        public byte[] FileDate { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileSize { get; set; }
        public Nullable<int> LetterID { get; set; }
    
        public virtual Letter Letter { get; set; }
    }
}
