//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Letter()
        {
            this.AttachFiles = new HashSet<AttachFile>();
            this.ReferenceLetters = new HashSet<ReferenceLetter>();
            this.SendLetters = new HashSet<SendLetter>();
        }
    
        public int LetterID { get; set; }
        public string LetterSubject { get; set; }
        public string LetterAbstract { get; set; }
        public string LetterText { get; set; }
        public string LetterNumber { get; set; }
        public byte SecurityType { get; set; }
        public byte LetterTypeAction { get; set; }
        public byte LetterFollow { get; set; }
        public byte LetterAttachment { get; set; }
        public byte LetterResponse { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<byte> BayganiType { get; set; }
        public byte LetterType { get; set; }
        public byte DraftType { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> AnswerDeadline { get; set; }
        public string Reference { get; set; }
        public Nullable<int> ReplyRetterID { get; set; }
        public string LetterFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttachFile> AttachFiles { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenceLetter> ReferenceLetters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SendLetter> SendLetters { get; set; }
    }
}
