//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewID { get; set; }
        public int UserID { get; set; }
        public string Subject { get; set; }
        public string NewsText { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public byte[] FileNews { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<byte> IsSend { get; set; }
    
        public virtual User User { get; set; }
    }
}
