//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Note()
        {
            this.SendNotes = new HashSet<SendNote>();
        }
    
        public int NoteID { get; set; }
        public string SubjectNote { get; set; }
        public string SubjectMatn { get; set; }
        public Nullable<int> UserID_Sender { get; set; }
        public string FullNameSender { get; set; }
        public Nullable<System.DateTime> CreateDateNod { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SendNote> SendNotes { get; set; }
    }
}
