//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceLetter
    {
        public int ReferenceLetterID { get; set; }
        public int LetterID { get; set; }
        public int UserIDReference { get; set; }
        public int UserIDReciveID { get; set; }
        public string FullNameRecive { get; set; }
        public string FullNameReference { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public Nullable<int> ReadType { get; set; }
        public string Description { get; set; }
        public Nullable<int> LevelNumbers { get; set; }
        public Nullable<long> IsShow { get; set; }
    
        public virtual Letter Letter { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
