//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendLetter
    {
        public int SendLetterID { get; set; }
        public System.DateTime SendDateLetter { get; set; }
        public int LetterID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> UserID_SendLetters { get; set; }
        public Nullable<long> IsRead { get; set; }
        public string FullNameReciveLetters { get; set; }
        public Nullable<long> IsShow { get; set; }
        public string FullNameSender { get; set; }
    
        public virtual Letter Letter { get; set; }
        public virtual User User { get; set; }
    }
}
