//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendNote
    {
        public int SendNoteID { get; set; }
        public Nullable<int> UserID_Recive { get; set; }
        public Nullable<int> NoteID { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string FullName { get; set; }
    
        public virtual Note Note { get; set; }
        public virtual User User { get; set; }
    }
}
