//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int LoginID { get; set; }
        public int UserID { get; set; }
        public string ComputerName { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> EnterDateTime { get; set; }
        public Nullable<System.DateTime> ExitDateTime { get; set; }
        public Nullable<float> SomHors { get; set; }
    
        public virtual User User { get; set; }
    }
}
