//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetJob
    {
        public int SID { get; set; }
        public int UserID { get; set; }
        public int JobID { get; set; }
        public Nullable<System.DateTime> SetDateJob { get; set; }
        public Nullable<System.DateTime> EndDateJob { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
    }
}
