//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_jobss
    {
        public int JobID { get; set; }
        public string JobName { get; set; }
        public Nullable<int> Job_LevelId { get; set; }
        public Nullable<int> DeterminaljobLevelid { get; set; }
        public Nullable<int> countchild { get; set; }
    }
}
