//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Users
    {
        public int UserID { get; set; }
        public string UserFirstName { get; set; }
        public string UserFamily { get; set; }
        public string UserName { get; set; }
        public string PersonalCode { get; set; }
        public string UserEmail { get; set; }
        public string FarsiGender { get; set; }
        public string FarsiActivity { get; set; }
        public string UserTell { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string UserImage { get; set; }
        public string UserSignturess { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte Gender { get; set; }
        public byte Activity { get; set; }
        public string JobName { get; set; }
        public Nullable<System.DateTime> EndDateJob { get; set; }
        public byte status { get; set; }
    }
}
